version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 029328341406
    IMAGE_NAME: my-docker-image
    REPO_NAME: test
    IMAGE_TAG: react-latest


phases:
 
  
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
      - echo Tagging the Docker image...
      - docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      
      - aaws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h1s4n2q3
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag my-docker-image:react-latest public.ecr.aws/h1s4n2q3/test:react-latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

